### ISSUE TITLE
Home >> Menu

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/artesol-theme#1]
Menu da home é dentro do bloco inicial: 

![bloco_1_home](https://cloud.githubusercontent.com/assets/3632627/5886450/115f0a4c-a387-11e4-8b42-d685818a24aa.png)

Assim como a busca e o link para voltar à Home.

Existe uma idéia de na home o link do logo não ir para ele mesmo e sim para a página de apresentação da ArteSol

O Menu deve ser acionado com clique e ficaria assim aberto: 
![menu-hover](https://cloud.githubusercontent.com/assets/3632627/5886575/97072b10-a38d-11e4-9858-0f63388ca336.png)

**Comment by everaldomatias** [comment]
Como esse logo/menu aparece apenas na Home, o link dela estará sempre linkando para /apresentacao caso a página exista.

**Comment by diegorojas** [comment]
Na verdade Eve, não é só na Home não. Vou usar nas paginas de listagem como archive de noticias, de categorias e de serviços. Assim seria isso mesmo, só na home ou (_front) que deveria ir para a apresentação, mas isso ainda pode ser melhorado.

**Comment by matheusgimenez** [comment]
Deveria estar funcionando já.. não funcionou?

**Comment by diegorojas** [comment]
Ta sim matheus, eu so transferi todas as issues para vc, amanhã vou rever o que está feito e o que não está e ai deixo tudo atualizado.

O projeto está como você deixou, o Eve não conseguiu avançar então siga o que você sabe que está feito.

**Comment by diegorojas** [comment]
Blza?

**Comment by matheusgimenez** [comment]
Sem problemas

**Comment by everaldomatias** [comment]
@matheusgimenez você fez essa issue? Se sim, por favor aplique no brasawp/artesol
