### ISSUE TITLE
Ícone do box Projetos

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/artesol-theme#10]
@diegorojas semelhante a #9, preciso que aqui você gere esse icone e substitua no tema. Pois no PSD ele estava mesclado com o bg.

![image](https://cloud.githubusercontent.com/assets/1918474/6539135/983c620a-c44b-11e4-80f7-5569d5956d80.png)

**Comment by diegorojas** [comment]
A mesma coisa, comentada nas issues #5 e #6, isso deverá ser feito direto pelo dashboard.
