### ISSUE TITLE
Estrutura de template interno institucional - page-institucional.php

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/artesol-theme#12]
Com sidebar especifica, parte superior com imagem destacada e frase que pode ser o Resumo (excerpt).
![layout_artesol_institucional_v4](https://cloud.githubusercontent.com/assets/3632627/6789406/c4f789ce-d17e-11e4-9e4b-3ec0c77d9903.jpg)

Parte inferior vai ter chamada para Mapa, mas envio o PSD e faço outra issue sobre isso.

**Comment by matheusgimenez** [comment]
feito no branch institucional

**Comment by matheusgimenez** [comment]
resolvido o problema do menu
