### ISSUE TITLE
Page Template Rede

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/artesol-theme#13]
@matheusgimenez essa página será um page template mais elaborado, com ACFs específicos para ela.

Estou criando essa issue apenas como start desse processo, nas issues seguintes eu quebro em partes.

O PSD disso está em /Artesol/3.0 Execução/Layouts/Home_Artesol_01_rede_v04.psd

**Comment by diegorojas** [comment]
Manos, é importante lembrar que nem tudo precisa ser ACF. A lógica do conteudo que está em beta.brasa.art.br/artesol é de paginas e sub-paginas. Vejam o fluxograma!

**Comment by everaldomatias** [comment]
Te perguntei isso ontem Diego.
Aponte por favor a melhor lógica para isso?

**Comment by diegorojas** [comment]
Tentei apontar nas outras issues especificas. Vc viu? Rola?

**Comment by diegorojas** [comment]
Eu tb já tinha falado da lógica de paginas e sub-paginas lá no ColetivoWP :)

**Comment by diegorojas** [comment]
Ei Pessoal, nova versão da Pagina da rede para ficar registrada.
![home_artesol_01_rede_v05](https://cloud.githubusercontent.com/assets/3632627/8133218/5e5d2980-10fd-11e5-9307-e408f2817dec.jpg)

Houve uma uma pequena alteração que ficara entre Tipologias e Beneficios, os antigos 4 botões de participe, agora se tornam um único.

![home_artesol_01_rede_alteracao](https://cloud.githubusercontent.com/assets/3632627/8133260/9a0faeda-10fd-11e5-83ad-331f9efe7831.jpg)

**Comment by diegorojas** [comment]
Tb subi o PSD novo para o Drive

**Comment by diegorojas** [comment]
Man, 

Aqui ainda preciso de uma descrição para cada tipo de membro :(

Ou ficaria num modal como tipologia e ali um botão para o archive ou seria uma descrição lá no próprio archive de alguma forma :(

**Comment by diegorojas** [comment]
Os 4 tipos de membro não vão ter modais não, é link direto para o archive da cada um mesmo.

Mas temos ainda o seguinte para fazer aqui. Veja no PSD novo o desenho para o template do brasa slider "Destaques da Rede", precisa puxar o titulo da página ou da imagem que estamos destacando.

![destaques-rede](https://cloud.githubusercontent.com/assets/3632627/8499788/92b9e022-216c-11e5-9f99-c1303798b5de.png)

**Comment by diegorojas** [comment]
Para finalizar esta pagina, depois de conseguirmos jogar as infos no mapa.artesol.org.br precisa trocar no template a chamada para o mapa certo tirand do a.brasawp.art.br/artesol
