### ISSUE TITLE
Header (com sub-menu)

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/artesol-theme#14]
Esse header pode ser reaproveitado do CPT Projetos.

E precisa adicionar o submenu. Esse submenu são âncoras para essa mesma página. Por enquanto podemos fazer na mão até encontrarmos uma solução de deixar isso dinâmico.

![arte1](https://cloud.githubusercontent.com/assets/1918474/7020481/b6a29446-dcef-11e4-94c4-ebfa0edfd633.jpg)

**Comment by diegorojas** [comment]
Especificamente o menu com scroll down vai ser usado em diversas páginas como essa. Isso seria importante já criarmos uma forma de fazer alguma coisa pelo dashboard. Mas se não der não deu. Só pensem em um código e em menus fáceis de se replicar para as outras páginas como essa.

**Comment by everaldomatias** [comment]
A forma mais simples seria com menus do próprio WP, e no page template colocar em ACF campos para a pessoa setar o ID do elemento que vai receber a âncora.

O que acham @diegorojas e @matheusgimenez ?

**Comment by diegorojas** [comment]
Eu acho que seriam bem legal! Algo por ai já ajudaria bastante!

**Comment by matheusgimenez** [comment]
Porque não fazer tudo por menu do WP? A pessoa colocaria o link como #id-do-elemento e boa!

**Comment by everaldomatias** [comment]
É isso mesmo @matheusgimenez
