### ISSUE TITLE
Section Conheça a Rede

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/artesol-theme#15]
Campos ACF no page template 'Rede'.

O botão também pode ser em ACF.

![arte1](https://cloud.githubusercontent.com/assets/1918474/7020586/8d542cf2-dcf0-11e4-96fd-00de043e5836.jpg)

**Comment by diegorojas** [comment]
Se fizerem tudo com ACF não vai bater com o conteúdo que já está em beta.brasa.art.br/artesol. Para facilitar a nossa publicação depois e a manutenção do conteúdo diss,  ai seriam. "Conheça a Rede" uma pagina filha de "A Rede" e as outras 6 seriam filhas da "Conheça a Rede" portanto netas da "A Rede". Essa lógica se repete em vários templates, precisamos manter assim.

**Comment by diegorojas** [comment]
O botão e outros botões como esse concordo plenamente que precisarão estar em ACF.

**Comment by everaldomatias** [comment]
@matheusgimenez tudo bem dessa forma?

Assim cada um desses itens não são ACFs, mas sim sub-pages de "Conheça a Rede".

**Comment by matheusgimenez** [comment]
feito no ultimo commit
