### ISSUE TITLE
Section Tipologia

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/artesol-theme#16]
Pela conversa que vi isso são taxonomias. Precisamos definir como add thumbnail de forma rápida a isso.

![arte1](https://cloud.githubusercontent.com/assets/1918474/7020689/7f435006-dcf1-11e4-948c-84d20076d808.jpg)

**Comment by diegorojas** [comment]
Exato eve, isso é uma taxonomia do CPT Projetos que não precisa só de thumb como precisa de uma descrição completa em modal ou tipo numa single.

**Comment by diegorojas** [comment]
Isso vai ser usado novamente lá no mapa para filtar as coisas e "categorizar" os artesãos

**Comment by everaldomatias** [comment]
@matheusgimenez podemos colocar ACFs nessa taxonomia, ou teremos que fazer na mão?

**Comment by matheusgimenez** [comment]
Com modal não rola isso.. Mas como o Eve falou, podemos usar o ACF (eu nem sabia que o ACF tinha essa funcao, mas tem, hehe).

Ai no single podemos usar o template file taxonomy-{slug-da-taxonomy}.php pra exibir como um single

**Comment by diegorojas** [comment]
Perfeito, vamo que vamo, para esse tipo de single usaremos a mesma estrtutura da page.php
