### ISSUE TITLE
Section Participe

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/artesol-theme#17]
Seção com links para conteúdos relacionados a como participar do projeto.

@diegorojas confirme por favor para onde esses itens levam (links).

@matheusgimenez aguardamos o posicionamento do Diego para seguir com essa issue.

![arte1](https://cloud.githubusercontent.com/assets/1918474/7020664/54a239d4-dcf1-11e4-8093-6098e5617a95.jpg)

**Comment by diegorojas** [comment]
Serim links para páginas simples, algumas com formulários e outras não. Aqui é ACF na veia mesmo.
