### ISSUE TITLE
Section Benefícios

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/artesol-theme#18]
Title e ACFs

![arte1](https://cloud.githubusercontent.com/assets/1918474/7020730/ba785536-dcf1-11e4-894f-e6bbf06a93a0.jpg)

**Comment by diegorojas** [comment]
Mesma lógica de Filha e Netas manos, é melhor. Quando "Beneficios" tiver conteúdo ficaria ali abaixo do título dele, antes dos 3 boxes, com a largura toda.

**Comment by everaldomatias** [comment]
Ok @matheusgimenez ?
