### ISSUE TITLE
Destaques (vide Home)

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/artesol-theme#19]
Copiar esses destaques que utilizamos na Home.

@diegorojas por favor explique melhor esse item marcado em vermelho.

![arte1](https://cloud.githubusercontent.com/assets/1918474/7020764/0936bf8c-dcf2-11e4-9f59-edfc07ffc834.jpg)

**Comment by diegorojas** [comment]
São destaques muito parecidos com os da home. Já feitos em opções e visualmente. Mas vai ficar estranho. Acho melhor repetir com os esquema de destaques que já estamos fazendo para a Home, mas agora na aba "A Rede", seriam destaque 1, 2 e 3.
