### ISSUE TITLE
Home >> Comercio e Artesanato

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/artesol-theme#2]
Dois blocos de destaque para internas:
![bloco_2_home](https://cloud.githubusercontent.com/assets/3632627/5886464/7e040954-a387-11e4-9f3c-2fb60bbf03c6.png)

Devem ter hover de ressaltar a fonte, ainda não pensado.

Precisam de opções para poder administrar qual imagem de fundo em cada uma.

Ver possibilidade de fazer posicionamento de blocos da home com drag em drop, asssim como o antigo eletro-widgets do HackLab.

**Comment by everaldomatias** [comment]
Não vou me preocupar com isso por enquanto:
"Ver possibilidade de fazer posicionamento de blocos da home com drag em drop, asssim como o antigo eletro-widgets do HackLab."

Acredito que falta escopar melhor essa ideia. Isso valeria para todos os box's, ou apenas esses do header?

Porque como isso estará como Options na administração, muito comum que a pessoa preencha na ordem que ela deseja, não?

**Comment by diegorojas** [comment]
Boa Eve, vamos facilitar sim e por hora vai para a dashboard.
