### ISSUE TITLE
Section Mapa

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/artesol-theme#20]
Adicionar o mapa da Rede.

@diegorojas nos confirme se isso é dinâmico ou apenas um print com link para o mapa.

![arte1](https://cloud.githubusercontent.com/assets/1918474/7020790/39e329b8-dcf2-11e4-859f-eb36e5771937.jpg)

**Comment by diegorojas** [comment]
A ideia é que isso seja tipo um iframe navegável. Deve estar puxando o mapa de tela cheia que estará em rede.artesol.org.br dinâmicamente sim.
