### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/artesol-theme#21]
O rodapé que já temos programado, aplicar nesse page template 'Rede'.

![arte1](https://cloud.githubusercontent.com/assets/1918474/7020807/5f3a7b9e-dcf2-11e4-8d86-fe7aef146e20.jpg)

**Comment by diegorojas** [comment]
isso tá fácil hein! get_sidebar ('rede'); :)

**Comment by everaldomatias** [comment]
@diegorojas faz:
git add --a
git commit -m "isso tá fácil hein!"
git push

já ajuda ;)
