### ISSUE TITLE
Criar Page Template Serviços

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/artesol-theme#23]
@matheusgimenez, segue o layout do archive desse template abaixo, vou quebrar em issues na sequência.

Segue como fez com a Rede. Qualquer dúvida, chama ai.

![layout_servicos](https://cloud.githubusercontent.com/assets/1918474/7112260/5c7fa69e-e19e-11e4-8061-4c92e69a1a5e.jpg)

**Comment by everaldomatias** [comment]
@diegorojas veja se essa ideia está coerente por favor.

**Comment by matheusgimenez** [comment]
Penso que poderia ser páginas e sub-páginas, sendo que a página mãe teria os options

**Comment by everaldomatias** [comment]
Vou alterar a descrição @matheusgimenez, manda Brasa dessa forma então.

**Comment by diegorojas** [comment]
Só para registrar que preciso renovar esse template, creio que vá precisar de ajuda para deixar tudo com width 100%.  Mas to jogando para mim.

![layout_servicos-v03](https://cloud.githubusercontent.com/assets/3632627/8356106/9579be16-1b29-11e5-91f9-e1dff443834a.jpg)

**Comment by diegorojas** [comment]
O layout v2 está lá na pasta do Drive também, acabei de conferir.

**Comment by diegorojas** [comment]
Não to conseguindo só configurar a parte do download de Portfolio. Já fiz uma pagina Portfolio.. mas num rolou, não entendi a lógica para configurar.
