### ISSUE TITLE
Home >> Slider

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/artesol-theme#3]
O slider da Home é uma proposta de inovação. Todos os posts destacados teriam duas formas de visualização.

Visualização em listagem:

![slider_home-listagem](https://cloud.githubusercontent.com/assets/3632627/5886470/ca509282-a387-11e4-8bc9-2b7ccfc094c3.png)

E visualização de um unico destaque grande:
![slider_home-unico](https://cloud.githubusercontent.com/assets/3632627/5886472/d7f66362-a387-11e4-9478-becaf811765e.png)

Isso é controlado pela chavinha superior direita, que deveria funcionar como um interruptor.

**Comment by everaldomatias** [comment]
@matheusgimenez você aplicou esse slider? é o BrasaSlider?

Você pode por favor aplicar ele no brasawp/artesol e configurar algum exemplo no admin?

**Comment by everaldomatias** [comment]
@matheusgimenez deixei algumas imagens de exemplo na biblioteca do site para você usar no slider ;)

**Comment by diegorojas** [comment]
Matheus, preciso entender como somar o metabox em cada post_type para selecionar qual vai para o slider qual não. Por hora preciso somar os Posts, só está em páginas atualmente.

**Comment by matheusgimenez** [comment]
Diego, veja:

https://github.com/brasadesign/artesol-theme/blob/master/fields.php#L290

Nessa linha é só vc duplicar a de cima, ficando por exemplo:
    array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 0,
    ),
    array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                    'order_no' => 1,
                    'group_no' => 0,
    ),

**Comment by diegorojas** [comment]
Valeu! Testando.

**Comment by diegorojas** [comment]
Cara, não rolou. Se eu uso isso, some o campo dos dois post_types, por hora substitui para post, que para mim já ajuda. Depois dá uma olhada nisso ok? Precisaremos também do post_type "projetos" nesse slider.
