### ISSUE TITLE
Download Monitor [ Publicações ]

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/artesol-theme#30]
@matheusgimenez manda Brasa nesse template, ele é a listagem dos itens adicionados via plugin Download Monitor ( https://wordpress.org/plugins/download-monitor/ ), essa página deve se chamar Publicações.

Acho que esse não é muito complexo, então vou manter em um issue só.

![layout_publicacoes](https://cloud.githubusercontent.com/assets/1918474/7305750/8f24560e-e9d6-11e4-99d9-56295a4246aa.jpg)

**Comment by matheusgimenez** [comment]
feito no ultimo issue

**Comment by everaldomatias** [comment]
Obrigado @matheusgimenez
