### ISSUE TITLE
Agenda Archive + Modal

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/artesol-theme#33]
@diegorojas preciso que nos ajude com a concepção que imaginou para a Agenda. Categoria, validade dos posts, fields e etc.

Abaixo segue layout do Archive Agenda. E na sequência o Modal que abrigará as informações, substituindo a single.

![layout_agenda](https://cloud.githubusercontent.com/assets/1918474/7345064/deaf068c-eca7-11e4-8968-2f0124e0c7e1.jpg)

Modal

![layout_agenda_modal](https://cloud.githubusercontent.com/assets/1918474/7345090/fbeec106-eca7-11e4-8fe0-6ba2e3c652e4.jpg)

**Comment by diegorojas** [comment]
Ei mans acho que aqui estamos falando de um query dos posts agendados da categoria "Agenda", não sei se seria um archive, uma category ou até um page template. A data a ser aproveitada é a de agendamento.

Os campos além do content seriam "Localização" e "Horário". Esqueçam da idéia de ressaltar eventos do dia nesse query, a ideia é ele virar um post mesmo e ganhar destaque no slider principal da home. Esclareceu?

**Comment by diegorojas** [comment]
Bom, deixando mais claro. Post da categoria "evento" que estiver agendado assim que for publicado deve virar "categoria" Noticia.

**Comment by diegorojas** [comment]
@matheusgimenez, espero que seja detalhe, mas os meses resumidos estão vindo em inglês. Sabe como mudar isso?

![mes-english](https://cloud.githubusercontent.com/assets/3632627/7418981/4e7af208-ef48-11e4-93db-7bc1ab931cc3.png)

@everaldomatias já enfrentamos problemas assim em versões anteriores da agenda, alguma luz?

**Comment by diegorojas** [comment]
Traduzir o mês dentro do modal também, só esta funcionando no query do archive por equanto.

**Comment by diegorojas** [comment]
Matheus, também temos uma questão aqui de chamar todos os eventos antigos que ja estavam na categoria. Podemos fazer um if de só mostrar no query os eventos que estiverem com a data via ACF preenchida? Ai vai ficar só o que elas estão fazendo a partir de agora e se quiserem recuperar algo, só setam a data que aparece. O problema está em diferenciar ano, alguém com alguma idéia?

**Comment by diegorojas** [comment]
Etcha... isso não tá feito não cara.. Pode me orientar rapidão para eu fazer aqui?

**Comment by diegorojas** [comment]
Matheus, cliente falou o seguinte:
"Fui atualizar a agenda e notei que ela está ficando bagunçada as datas ficam na ordem de postagem, e não na ordem das datas dos eventos."
Pode confirmar se está faltando um order by lá e se sim, coloque por favor. ok?

**Comment by matheusgimenez** [comment]
Tem orderby já.. estranho..
