### ISSUE TITLE
Comércio Justo

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/artesol-theme#34]
@matheusgimenez mesmo sistema de sub-pages.

Alí onde está "Princípios", pode ser um PNG no código mesmo, por enquanto nem precisa ser dinâmico, beleza?

Qualquer dúvida chama lá no Telegram.

![layout_comercio_justo](https://cloud.githubusercontent.com/assets/1918474/7348628/7b06861a-ecc9-11e4-847d-13193e951783.jpg)

**Comment by diegorojas** [comment]
@matheusgimenez esse cabeçalho vermelho, não precisa ser option.. É bg da área ali mesmo.. O texto que aparece ali é o resumo da página

**Comment by diegorojas** [comment]
Já a ultima faixa "Atuação da Artesol" deve ter a lógica de serviços, colocando a imagem destacada da sub-page de fundo. Mas com um filtro laranja em cima mesmo, para alaranjar qualquer foto.

**Comment by diegorojas** [comment]
O logo da World Fair Trade Organization pode estar direto no template tb, não precisa ser option.
