### ISSUE TITLE
Template de Resultado de Busca

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/artesol-theme#37]
Matheus usar a carcaça do single para desenvolver o query de busca e sua paginação:

![layout_artesol_search](https://cloud.githubusercontent.com/assets/3632627/7391730/8296c5a2-ee59-11e4-857f-21a01daa0377.jpg)

Rodapé padrão.

**Comment by diegorojas** [comment]
Se o resultado for de página, imagino que a categoria some a a data se mantém.

**Comment by diegorojas** [comment]
Matheus, duas coisas, um pequeno bug da posição da caixa ao acionar a busca novamente:

![bug-search](https://cloud.githubusercontent.com/assets/3632627/7418269/06ceb458-ef43-11e4-800e-44b6eede8e74.png)

E quando não tiver resultados como no exemplo precisava de um: "Sua busca não obteve resultados, tente novamente usando outro termo."

**Comment by matheusgimenez** [comment]
feito no ultimo commit - branch category (nao troquei)

**Comment by matheusgimenez** [comment]
feito no ultimo commit - branch category (nao troquei)
