### ISSUE TITLE
Criar if para Single sem Imagem

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/artesol-theme#39]
Aqui é só criar uma opção para mostrar o título do post quando não houver imagem destacada.

![layout_single_s_imagem](https://cloud.githubusercontent.com/assets/3632627/7391962/ed69ff56-ee5a-11e4-969c-2c7ec8e8e224.jpg)

**Comment by matheusgimenez** [comment]
feito no ultimo commit - branch category (nao troquei)
