### ISSUE TITLE
Home >> Bloco de Serviços e Agenda

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/artesol-theme#4]
2 blocos de informação que devem ter seus conteúdos, títulos e cores(de título e botão) editáveis:

![bloco_servicos_agenda](https://cloud.githubusercontent.com/assets/3632627/5886485/d0f929ae-a388-11e4-8048-3a3cbdd97dec.png)

**Comment by matheusgimenez** [comment]
Isso vai ser option? widget?

**Comment by everaldomatias** [comment]
Acho melhor Option, para não correr o risco do usuário colocar muitos widgets alí.
