### ISSUE TITLE
Criar If para Page com Imagem

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/artesol-theme#41]
Ei matheus, pensei em uma opção de página simples para colocar o titulo e o resumo num cabeçalho de imagem

![layout_page_c_imagem](https://cloud.githubusercontent.com/assets/3632627/7413401/e03d499c-ef21-11e4-9eaa-174cc5ff1333.jpg)

**Comment by matheusgimenez** [comment]
feito no ultimo commit - branch category (nao troquei)
