### ISSUE TITLE
Aplicar Busca no Header Interno

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/artesol-theme#43]
Ei Matheus, preciamos applicar a busca no header interno, fica assim o icone:

![header-interno](https://cloud.githubusercontent.com/assets/3632627/7613047/b9f488fc-f964-11e4-9175-a8e65fa5eaa2.jpg)

E depois do clique abre a mesma caixa que na home mas embaixo:

![header-interno-click](https://cloud.githubusercontent.com/assets/3632627/7613057/c77e80a4-f964-11e4-9b9d-6231217c1141.jpg)

**Comment by matheusgimenez** [comment]
feito no ultimo commit
