### ISSUE TITLE
CPT / Archive Membros da Rede

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/artesol-theme#45]
Criar novo CPT baseado em Projetos com os mesmos campos, mas usaremos no single. No archive fazer em cima da carcaça do Publicações como abaixo:

![layout_membros-da-rede-v02](https://cloud.githubusercontent.com/assets/3632627/8133283/d0d9cbf8-10fd-11e5-9faa-2b0ec830d775.jpg)

A diferença desse CPT é que ele deverá manter o metadado de que é do usuário x do mapa, que estará em mapa.artesol.org.br

No cabeçalho precisamos de Link para as variaveis que somou em membros: Artesão ou Mestre, Cooperativas ou Associações, Lojistas e Aceleradoras e Governos.

![header-membros](https://cloud.githubusercontent.com/assets/3632627/8133366/55aea8b2-10fe-11e5-964e-8f75d045a2bb.jpg)

O Filtro seria dinâmico, de Tipologias. 

PSD está no drive, na pasta ArteSol

**Comment by diegorojas** [comment]
Sobre isso aqui temos várias coisas, tentando registrar quase tudo aqui, qq coisa falamos mais ok matheus?

Mudança de nome da taxonomia Tipologia => Saberes e Fazeres

Artesão/Meste, Associação/Cooperativa são os 2 tipos principais de Membros que têm a taxonomia agora "Saberes e fazeres" e também uma nova chamada "Categoria" de fato com as seguintes:
- Arte Popular
- Indígena
- Referência Cultural
- Tradicional
- Conceitual
- Grande Escala

Essa precisa ser criada. 

Agora tenho a clareza que essas taxonomias não devem estar disponíveis para Lojistas e Aceleradoras e Governo, que virou=> Agentes de Apoio

Precisamos criar uma nova taxonomia "Perfil" para os "Agentes de Apoio" que também seria filtrável:
- Programas Governamentais
- Instituições Culturais
- Empresas e Profissionais
- ONGs

Todos os tipos de Membros e Projetos, deve ter um select de Estados do Brasil, isso também seria filtrável no archive membros e no archive projetos.

Temos como filtros nos Archives Membros, o seguinte:
Artesão/Meste - Saberes e Fazeres, Categoria, Estado 
Associação/Cooperativa - Saberes e Fazeres, Categoria, Estado
Lojistas - Estado
Agentes de Apoio - Perfil e Estado

**Comment by diegorojas** [comment]
Veja o novo visual para os filtros:

![header-membros-filtros](https://cloud.githubusercontent.com/assets/3632627/8500274/e83bbe54-2170-11e5-97b4-25702127e36a.jpg)

**Comment by diegorojas** [comment]
Temos algum bug na paginação de membros depois de filtrados... 

A paginação exibida é a de todos os membros, e ao clicar na pagina 2, não funciona.. 

![paginacao-bug](https://cloud.githubusercontent.com/assets/3632627/10370424/26f577e4-6db5-11e5-9bc0-20cf0d7d2e15.png)

Precisa manter o funcionamento conforme está em Projetos, lá ta funcionando perfeito. Pode testar aqui: http://artesol.org.br/membros/?type_pin=associacoes&filter_type=bordado

**Comment by matheusgimenez** [comment]
feito no ultimo issue
