### ISSUE TITLE
CPT / Single Membros da Rede

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/artesol-theme#46]
Criar a Single em cima da Single de Projetos

![layout_membro-single](https://cloud.githubusercontent.com/assets/3632627/8133870/45784612-1101-11e5-9c89-94ea77642884.jpg)

A galeria de Produtos é simplesmente um query das imagens anexadas naquele Post, com possibilidade de abrirem no Carrousel do JetPack.

PSD no Drive tb

**Comment by diegorojas** [comment]
O rodapé é só usar o de como apoiar pessoa fisica

**Comment by diegorojas** [comment]
Olá meu, vamos lá fazer essa definição direito agora... Temos os seguinte esse conteúdo aqui é hibrido. alguns campos vêm do usuário lá do mapa e outros não, mas de qualquer forma eles precisam de um vínculo sim, mas não são a mesma coisa.

Os dados de cada usuário que devem vir do Mapa são:

Nome:
Tipo de Membro:
Tipologia:
Sobre:
O Artesanato e a Técnica: 
Galeria de Fotos:
Endereço:
Contato: ( Nome do usuário )
Telefones:
E-mail:
Facebook:
Site:

**Comment by diegorojas** [comment]
@matheusgimenez ainda precisa ver de puxar  na single alguns dos dados listados no comentário acima não?

**Comment by diegorojas** [comment]
Repare no header tb, diferente, sem os botões e com o breadcrumb para definir qual é o tipo, ok?

**Comment by matheusgimenez** [comment]
Quanto aos dados, acabei nem vendo esse comentário seu. Eu fiz conforme estava na imagem. De qlq forma preciso de mais informações sobre onde vai ficar esses dados

**Comment by diegorojas** [comment]
Legal Matheus, tudo fica na tela de editar o usuário mesmo. 

Mas acabei de esclarecer com o cliente aqui que teremos que ter uma list select de estado em Projetos e em Membros também.

Ai Localização vai virar Cidade e estado dentro de uma lista de seleção

**Comment by diegorojas** [comment]
Matheus, aqui preciso desenhar e definir de fato o dado que terá em cada tipo de membro para preencher e mandar o visual de como vai ficar cada um. Estou fazendo aqui, mas reveja meu comentário acima e tente adiantar o header dessa single igual ao PSD mesmo, ok?

É importante que tenho aquela indicação após "Membros >>" de qual tipo de Membro se trata e que ela seja dinâmica, ok?

**Comment by diegorojas** [comment]
Matheus,

Não vou conseguir desenhar, então vou te pedir para fazer as opções/campos em cada membro e "cuspir" eles em cada template, depois eu resolvo no frontend via marcação, ok? Tudo o que tiver nessa lista deve aparecer no frontend.

Campos comuns entre todos:
Nome (title):
Sobre (content):
Estado (Select list):
Endereço (text + google maps?): 
Contato (text):
Telefones (text):
E-mail (link):
Facebook (link):
Site (link):

Artesão/mestre:
Taxonomias: Saberes e Fazeres (antiga Tipologia), Categoria (nova)
O Artesanato e a Técnica (text area): 

Associações/Cooperativas:
Taxonomias: Saberes e Fazeres (antiga Tipologia), Categoria (nova)
O Artesanato e a Técnica (text area):  

Lojistas:
Não possuem campos especificos, pelo que visualizei na conversa, é capaz de um dia ter uma taxonomia, mas elas ainda não têm essa clareza, por hora não faremos nada.

Agentes de Apoio:
Taxonomia: Perfil
Pública ou privada (selec list): 
Histórico (text area):

**Comment by diegorojas** [comment]
@matheusgimenez aqui ainda precisamos jogar todos os dados abaixo de cada user no front end...

Campos comuns entre todos:
Endereço (text ): 
Contato (text):
Telefones (text):
E-mail (link):
Facebook (link):
Site (link):

Ja estou vendo a forma de resolver com css, so preciso dos dados dinamizament puxados ok?
