### ISSUE TITLE
Home >> Link para Rede

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/artesol-theme#5]
Destaque para a Rede com possibilidade de edição do texto:

![bloco_rede_artesol](https://cloud.githubusercontent.com/assets/3632627/5886502/92d9b75a-a389-11e4-9aa1-2c7790450c51.png)

Reparar que o destaque de "como apoiar" vem por cima inteiro e não cortado

**Comment by everaldomatias** [comment]
@diegorojas isso aqui é um link para uma page? CPT? categoria?

**Comment by diegorojas** [comment]
É para uma page template especifica, A Rede

**Comment by diegorojas** [comment]
Esse destaque na home, deve ser tratado em Opções, como foram os superiores, só que agora com um campo a mais de imagem, que é o ícone, ok?

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by diegorojas** [comment]
Vejo que sobrou um começo de opções da pages institucional:

![sobrou](https://cloud.githubusercontent.com/assets/3632627/6881356/f1d55ba0-d53a-11e4-9e8f-40a154d6252c.png)

Pode sacar fora.

**Comment by diegorojas** [comment]
A mesma coisa que comentei na issue #6.. 
- Titulo
- Imagem Icone
- Descrição
- Imagem Background
- Link (URL )

**Comment by matheusgimenez** [comment]
feito no ultimo commit  - esqueci de trocar de branch.. foi no institucional mesmo :(
