### ISSUE TITLE
Template Produtos

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/artesol-theme#50]
Fazer mais um template dinâmico ou não para cada Tipologia de artesanato.

A galeria de imagens deve chamar a mesma de single-membros

O botão "veja mais" vai para a single-membros

![layout_produtos](https://cloud.githubusercontent.com/assets/3632627/8628247/b6d818e6-2727-11e5-9970-76847be510ff.jpg)

**Comment by diegorojas** [comment]
o Query de tipologia deve ser o mesmo de artesanato brasileiro e Rede

**Comment by diegorojas** [comment]
Aqui precisa somar os outros filtros além do estado como já tem em associações: Estado e Categoria

![produtos-filtros](https://cloud.githubusercontent.com/assets/3632627/10374907/0c234808-6dcc-11e5-910b-6bf5a431434c.png)

**Comment by matheusgimenez** [comment]
feito no ultimo issue
