### ISSUE TITLE
Home >> Link para Projetos

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/artesol-theme#6]
Link para projetos com possibilidade de edição de texto:

![bloco_projetos](https://cloud.githubusercontent.com/assets/3632627/5886503/c18e5966-a389-11e4-8405-4ee669f773ba.png)

**Comment by everaldomatias** [comment]
@diegorojas isso será um CPT?
@matheusgimenez assim que o Diego responder, operacionaliza isso por favor.

**Comment by diegorojas** [comment]
Sim, será!

**Comment by diegorojas** [comment]
Vamos lá manos.. "Projetos" será um CPT, vou fazer uma issue disso descrevendo melhor os custom fields, mas esse destaque na home, deve ser tratado em Opções, como foram os superiores, só que agora com um campo a mais de imagem, que é o ícone, ok?

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by diegorojas** [comment]
Matheus, preciso que faça como fez os de cima, preciso poder escolher a imagem de fundo e a imagem do icone desses quadros de baixo. Pode fixar em 2 quadros mesmo, não precisamos do repeat aqui.

A diferença é o que está como subtitulo nos dois de cima aqui vira descrição. Então são 5 campos:
- Titulo
- Imagem Icone
- Descrição
- Imagem Background
- Link (URL )

**Comment by matheusgimenez** [comment]
feito no ultimo commit  - esqueci de trocar de branch.. foi no institucional mesmo :(

**Comment by diegorojas** [comment]
Matheus, ainda não rolou cara... Num é isso, é para deixar mais flexível mesmo.. mas mantendo 4 elementos desses na home como máximo.

Quero o seguinte, 2 destaques Superiores e 2 Inferiores, podemos usar a o que você colocou como "options", para "Destaques":

![onde-deve-mexer](https://cloud.githubusercontent.com/assets/3632627/6905889/7ab80d74-d701-11e4-89c6-9b82cb7119eb.png)

E ai fazer em duas Abas, "Home" vira "Superiores" e cria uma"Inferiores".

**Comment by diegorojas** [comment]
Ai precisa tirar essas coisas nessa outra logica de repeat, que não quero aqui, vamos usar em outro lugar isso.

![o-que-apagar01](https://cloud.githubusercontent.com/assets/3632627/6905962/e4744174-d701-11e4-8aa2-f2171f54d40b.png)

E o aparente lixo que sobrou:

![o-que-apagar02](https://cloud.githubusercontent.com/assets/3632627/6905973/f736d2ea-d701-11e4-874e-2fb30c52f78b.png)

**Comment by matheusgimenez** [comment]
Não entendi qual o problema com os campos como estão hoje.. eu usei repeater só pra evitar eu fazer vários campos, mas ele está limitado a 2, daria pra aumentar esse valor

**Comment by diegorojas** [comment]
O repeater, fixa o tipo de destaque no radio button abaixo.. 

![classe-de-box](https://cloud.githubusercontent.com/assets/3632627/6928202/ec2df870-d7c8-11e4-8fea-cf034142ea91.png)

E por mais que esteja setado maximo de 2, da a falsa impressão que dá para ir somando.. não queria isso. 

Cara, faz como eu to falando, por favor! :)

**Comment by diegorojas** [comment]
Não serão esses tipode de destaque saca? Pode poderão construir outros destaques no futuro, ou ir mudando..

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by matheusgimenez** [comment]
feito no ultimo commit
