### ISSUE TITLE
Home >> Footer

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/artesol-theme#8]
Footer do site como um todo:

![rodape](https://cloud.githubusercontent.com/assets/3632627/5886553/b6db5016-a38c-11e4-81b4-99991a978d49.png)

Agora por parte, primeiramente fazer um mapa do site com menus dinâmicos, como no Polis:

![mapa-do-site](https://cloud.githubusercontent.com/assets/3632627/5886557/ccd32768-a38c-11e4-8d46-d15b809e4a23.png)

Infos do rodapé com opção de edição: 
![info-rodape](https://cloud.githubusercontent.com/assets/3632627/5886559/d39330e8-a38c-11e4-9509-ab36da17fca6.png)

Widget para social icons ou alguma forma que preferir, é melhor elas terem controle, novas redes sociais devem aparecer nesse rodapé ao longo do ano:

![rodape-social-icons](https://cloud.githubusercontent.com/assets/3632627/5886563/f20e42ce-a38c-11e4-8e24-aa238c29ab9e.png)

Blocos da direita não precisam de edição, somente a edição do destino dos links:

![bloco-foot-direita](https://cloud.githubusercontent.com/assets/3632627/5886568/3c6cf8e2-a38d-11e4-8760-19c96d228162.png)

Assim como botão "Download de release" de assessoria de imprensa, parceiros teria um botão igual para "Todos os parceiros"

**Comment by matheusgimenez** [comment]
O menu ta feito.. agora falta todo o resto hehe
