### ISSUE TITLE
Background do box Projetos

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/artesol-theme#9]
@diegorojas no PSD o icone e o título desse box estão mesclados com o background. Nessa issue você deve exportar o bg disso e substituir a imagem "bg-projetos.png"

![image](https://cloud.githubusercontent.com/assets/1918474/6539124/6f889ab8-c44b-11e4-86d0-7f648ed02d2c.png)

**Comment by diegorojas** [comment]
Comentei nas issues #5 e #6, devo conseguir fazer isso pelo dashboard, ok?
